# Generated by Django 6.0.6 on 2026-08-30 19:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='صورة الفئة')),
            ],
        ),
        migrations.CreateModel(
            name='StoreContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_owners', models.PositiveSmallIntegerField(default=1, verbose_name='عدد المالكين')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=150, verbose_name='اسم المالك')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('position', models.CharField(max_length=120, verbose_name='المنصب')),
                ('store_contact_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='store.storecontactinformation')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=100, verbose_name='اسم المؤسسة التجارية')),
                ('commercial_registration_number', models.CharField(max_length=30, unique=True, verbose_name='رقم السجل التجاري')),
                ('nation', models.CharField(choices=[('الجزائر', 'Alger')], max_length=10, verbose_name='الدولة')),
                ('wilaya', models.CharField(choices=[('45', 'النعامة / Naâma'), ('16', 'الجزائر / Alger'), ('31', 'وهران / Oran')], max_length=2, verbose_name='الولاية')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='موقع المتجر')),
                ('is_tax_registered', models.BooleanField(default=False, verbose_name='منشأتك مسجلة في الضرائب')),
                ('tax_document', models.FileField(blank=True, null=True, upload_to='tax_documents/', verbose_name='وثيقة التسجيل الضريبي')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores_information', to='store.category', verbose_name='فئة المتجر')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to=settings.AUTH_USER_MODEL)),
                ('store_contact_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.storecontactinformation')),
                ('store_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.storeinformation')),
            ],
        ),
    ]
