# Generated by Django 6.0.6 on 2026-08-31 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم قائمة الخيارات')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخيار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الخيار')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعرات الحرارية')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.optiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.menu')),
                ('options', models.ManyToManyField(blank=True, related_name='products', to='product.option')),
            ],
        ),
    ]
